### ISSUE TITLE
qmlbook.org up-to-dateness

### ISSUE THREAD

**Issue by bergmansj** [qmlbook/qmlbook.github.io#1]
When I found out about qmlbook.org I was enthousiastic about the wealth of good reading there, but confused about the apparent inactivity. The main page dates the last edit more than a year ago.
Luckily I found that this Github project is still active. 

_I firstly want to compliment you on the book_ and suggest that you provide a more clear link from qmlbook.org to this project and keep the last edit date more in sync.

Keep up the good work,
Jeroen

**Comment by e8johan** [comment]
Thanks for pointing this out. This is my fault. Juergen has been pushing forward with the book contents while I've been absorbed into the daily life of having young kids. I'm redirecting the qmlbook.org and qmlbook.com to the github project page asap. 

Again, thanks for pointing this out. I'm glad that you appreciate the book!
